name: Recurring Tasks Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call cron API
        run: |
          echo "Running recurring cron..."
          curl -L "${{ secrets.CRON_URL }}" \
          -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"